stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    - data/bank_credit_scoring.csv
    outs:
    - data/raw_data
  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
    - data/raw_data
    - src/data_preprocessing.py
    outs:
    - data/processed_data
  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
    - data/processed_data
    - src/feature_engineering.py
    outs:
    - data/feature_engineered_data
  model_building:
    cmd: python src/model_building.py
    deps:
    - data/feature_engineered_data
    - src/model_building.py
    outs:
    - models/model.pkl
  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
    - data/feature_engineered_data
    - models/model.pkl
    - src/model_evaluation.py
    metrics:
    - reports/metrics.json
